### ISSUE TITLE
Sharing maintenance work - first steps

### ISSUE THREAD

**Issue by amotl** [conda-forge/wetterdienst-feedstock#53]
Dear Kai,

thank you very much for adding @gutzbenj and me as maintainers to this repository. As we have not been using Conda before too much, we may need some assistance.

For the matter of making a start, shall I just go ahead, and acknowledge the PR #45, in order to build and release Wetterdienst 0.39.0? I figure that the machinery will recognize my acknowledgement and conclude all further steps?

When all goes well, I will follow up with the same procedure for versions 0.40.0 and 0.41.0 as well? That sounds too easy to be true!?

With kind regards,
Andreas.

**Comment by kmuehlbauer** [comment]
@amotl If you think only the latest version 0.41 is necessary you might just merge that PR, all others will be closed without creating these versions. Otherwise go ahead step by step.

**Comment by amotl** [comment]
Thank you. I will go ahead step by step. Maybe some people will need the dedicated versions to hunt down for regressions of any kind. Good to have to whole history published then.

**Comment by amotl** [comment]
Hi again,

it looks like it will only work for newly created PRs. On #45, even after acknowledging, I don't see a merge button.

![image](https://user-images.githubusercontent.com/453543/182206759-5b766f2d-9474-4261-8c74-d7f4cfdf0aa3.png)

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

as reported at https://github.com/conda-forge/wetterdienst-feedstock/pull/52#issuecomment-1201509919 ff., we might still need memberships with write permissions on the repository to be able to conclude the necessary steps like merging PRs.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Apologies. I missed the invitation to the repository delivery by email and GitHub apparently does not display it on the user interface in any meaningful way. I've just merged #45 and will continue doing so with the others, as planned.

Thanks again for your support!

**Comment by amotl** [comment]
Are there any guesses how long it will take through the machinery to be visible on https://anaconda.org/conda-forge/wetterdienst?

**Comment by kmuehlbauer** [comment]
It normally takes up to two hours to trickle through the CDN.

**Comment by kmuehlbauer** [comment]
@amotl Sorry for being not more in the loop yesterday. I'll elaborate a bit more on the foundations of conda-forge:

- Most of the hard parts of the machinery is backed by bots [1].
- The maintaining part is described in [2].
- Updating recipes can be done automatically via `regro-autotick-bot` (we just have to wait a bit for the bott to detect the new version on PyPI and issue the PR)
- If we are eager to have the new version, we can issue a PR from our forks [3]
- But we need to take care all the global pinnings are at their last state (regro-bot would take care of this) [4]
- For pinning please refer to [5]
- If we have a test suite (rather short, only basic things to check correct build) we can run those by activation in meta.yaml (currently just importing) https://github.com/conda-forge/wetterdienst-feedstock/blob/9fbb91fed18d4fa0d4fccf35e937ee2a18048d4b/recipe/meta.yaml#L57-L59
- Configuring conda-forge.yml [6]

I'm having a hard time to understand which are required runtime dependencies of `wetterdienst` and which are optional. So the requirements run section in meta.yaml would need some expert eyes on it.

[1] - https://conda-forge.org/docs/maintainer/infrastructure.html#admin-web-services
[2] - https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-packages
[3] - https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-recipes
[4] - https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks
[5] - https://conda-forge.org/docs/maintainer/pinning_deps.html
[6] - https://conda-forge.org/docs/maintainer/conda_forge_yml.html

**Comment by amotl** [comment]
Dear Kai,

thank you for this extensive list of resources. I think I will be able to handle it after running some actions yesterday, also getting into a slight conversation with the `regro-autotick-bot` ;].

Thanks again for giving us permissions here, so we can maintain releases on our own behalf. I hope it will save you some time in the future.

For improving the list of runtime requirements, I've just created #57.

With kind regards,
Andreas.
