### ISSUE TITLE
Improve runtime dependencies

### ISSUE THREAD

**Issue by amotl** [conda-forge/wetterdienst-feedstock#57]
Hi there,

at https://github.com/conda-forge/wetterdienst-feedstock/issues/53#issuecomment-1202058124, @kmuehlbauer said:

> I'm having a hard time to understand which are required runtime dependencies of `wetterdienst` and which are optional. So the `requirements.run` section in `meta.yaml` would need some expert eyes on it.

With kind regards,
Andreas.

https://github.com/conda-forge/wetterdienst-feedstock/blob/dbcf6e9b3570c7627d86b1846b2627b7f942c6c0/recipe/meta.yaml#L25-L55

**Comment by amotl** [comment]
Hi again,

from my perspective, that list does not look bad at all. At the first sight, I am not able to identify any wrong item in this list. Maybe @gutzbenj also wants to check and add additional thoughts here?

Cheers,
Andreas.

**Comment by gutzbenj** [comment]
@amotl that list doesn't look bad indeed. We could try to opt-out PyPDF2, as I think it is only used to parse meta information from DWD at this moment.

**Comment by amotl** [comment]
Hi again,

finally, https://github.com/earthobservations/wetterdienst/commit/543ceb4f7 will significantly reduce dependencies maybe previously declared to be needed at runtime.

Based on this change, and the next release, we may want to revisit the corresponding conda configuration.

With kind regards,
Andreas.

**Comment by amotl** [comment]
I've just reviewed the list of dependencies again and believe they are good as they are. Feel free to reopen if you think differently.

**Comment by amotl** [comment]
Hm. Do we want to add those?

### Packages found by source code inspection but not in the meta.yaml:
- plotly
- dash-bootstrap-components
- fastapi
- utm
- shapely
- pytz
- dash
- autovizwidget
- finesse

**Comment by amotl** [comment]
### Packages found in the meta.yaml but not found by source code inspection:
- cachetools
- requests-ftp
- beautifulsoup4
- deprecation
- importlib_metadata
- dataclass-wizard

From those, I think we can remove all but `

- No traces for `cachetools`, `dataclass-wizard`, `deprecation`, `importlib_metadata`, and `requests-ftp. I guess those can be safely removed?
- `beautifulsoup4` is only used within `tests/ui/explorer/test_explorer.py`, so I think it is also safe to remove from the list of runtime dependencies.

**Comment by amotl** [comment]
I've submitted #71, which just follows the suggestions by `regro-cf-autotick-bot`.

**Comment by amotl** [comment]
I think we can consider the improvement to be concluded. Thanks for your support, @xylar!
