### ISSUE TITLE
Automatically convert versioned dependencies from `poetry.lock` to Anaconda's `meta.yaml`

### ISSUE THREAD

**Issue by amotl** [conda-forge/wetterdienst-feedstock#77]
### Comment:

Hi there,

coming from a suggestion by @xylar at https://github.com/conda-forge/wetterdienst-feedstock/pull/76/files#r1034481764, I am wondering whether there is no utility program already, which assists in creating/updating the `requirements` section in [recipe/meta.yaml](https://github.com/conda-forge/wetterdienst-feedstock/blob/main/recipe/meta.yaml), using the `poetry.lock` file as input.

Of course, it should adhere to the semantics outlined by @xylar in detail. Thank you very much!

> Note that `^1.3` in a `pyproject.toml` is equivalent to `>=1.3,<2.0` here in the `meta.yaml` (which doesn't know about `^`).  But versions starting with `0.` are a special case so `^0.8` is the same as `>=0.8,<0.9`, for example.

With kind regards,
Andreas.

**Comment by xylar** [comment]
There is a tool that does this from `setup.py`: https://github.com/conda-incubator/grayskull.  Grayskull doesn't yet fully support `pyproject.toml` files, just `seutp.py` but the PyPI version of `wetterdienst` has such a `setup.py`, it just doesn't look quite right.

I use `grayskull` to update the vast majority of the packages I maintain and I have a script for making that easy:
https://gist.github.com/xylar/13f003dc507f532bc065719d6e49be2f

I don't believe you would want to use `poetry.lock`.  My understanding is that those dependencies are stricter than what is in the `pyproject.toml` and they wouldn't be appropriate for conda-forge.

**Comment by amotl** [comment]
Hi Xylar,

thanks for suggesting Grayskull [^1], this looks excellent. Let me also add `pip-tools` [^2], which fits into the same category of tools. Maybe both programs can be combined to create a `pyproject.toml -> requirements.txt -> meta.yaml` pipeline, or such?

With kind regards,
Andreas.

[^1]: https://github.com/conda-incubator/grayskull
[^2]: https://github.com/jazzband/pip-tools

**Comment by amotl** [comment]
Oh, _here_ we go. -- https://github.com/python-poetry/poetry-plugin-export/issues/159

**Comment by amotl** [comment]
Excellent, thanks! Is it something we should add to an automated workflow now, or would it be a manual process to regularly convert `pyproject.yml` to the Conda specification file?

**Comment by xylar** [comment]
I run a script with each update but I run it manually and I don't think we want to try to automate it because maintainer intervention is often required.

https://gist.github.com/xylar/13f003dc507f532bc065719d6e49be2f

**Comment by amotl** [comment]
Hi again,

I am closing this in favor of GH-103. Your support on this topic of Anaconda dependency management is true gold, @xylar. We hope you can irregularily keep up the spirit to continue supporting us here, like now where we are aiming to modernize a bit.

With kind regards,
Andreas.
